### ISSUE TITLE
Support pytest version >= 4.1

### ISSUE THREAD

**Issue by kondratyev-nv** [ropez/pytest-describe#18]
pytest-describe plugin is not working with pytest 4.0 or later. 

```
=========================================== ERRORS ============================================
_______________ ERROR collecting test/test_samples/pytest/test/describe_test.py _______________
.tox/py27/local/lib/python2.7/site-packages/pytest_describe/plugin.py:110: in _getobj
    return self._importtestmodule()
.tox/py27/local/lib/python2.7/site-packages/pytest_describe/plugin.py:119: in _importtestmodule
    copy_markinfo(module, self.funcobj)
.tox/py27/local/lib/python2.7/site-packages/pytest_describe/plugin.py:60: in copy_markinfo
    from _pytest.mark import MarkInfo
E   ImportError: cannot import name MarkInfo
!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================== 1 error in 0.75 seconds ===================================
```

This error appears for the test from sample 

```python
import pytest


def describe_list():

    @pytest.fixture
    def list():
        return []

    def describe_append():

        def adds_to_end_of_list_passed(list):
            list.append('foo')
            list.append('bar')
            assert list == ['foo', 'bar']

    def describe_remove():

        @pytest.fixture
        def list():
            return ['foo', 'bar']

        def removes_item_from_list_passed(list):
            list.remove('foo')
            assert list == ['bar']
```

It looks like this happens due to changes in mark API since version 4.0, for example, see https://github.com/pytest-dev/pytest/blob/master/doc/en/deprecations.rst#somefunctionmarkname.

**Comment by Pankejk** [comment]
I like this plugin and I have the same issue. +1

**Comment by kondratyev-nv** [comment]
@ropez I have tried to run tests with various versions, and it looks like no main code changes needed for newer python versions and pytest up to 4.0.2. I think of making a PR on this at least.

As for the upper pytest versions, I'll take a look.

**Comment by ropez** [comment]
Sorry, I haven't had time to look into this. Are you saying that the issue with importing `MarkInfo` was not a problem after all?

**Comment by kondratyev-nv** [comment]
@ropez This is the problem for pytest >= 4.1. Everything is fine with the previous versions, and I have added a couple of tests to be sure. Please see PR #19.

**Comment by ropez** [comment]
Right, I was a little bit confused because you wrote "4.0 or later" in the original post. I will see if I find some time to look for a solution for 4.1 then.

**Comment by kondratyev-nv** [comment]
@ropez It looks like I have a working solution. However, the tests are failing with the latest pytest version due to the bug in pytest https://github.com/pytest-dev/pytest/issues/4649. I'll open a PR with the fix after the next pytest patch will be released.

**Comment by ropez** [comment]
@kondratyev-nv Maybe we should just change `-k` to `-m` in those test. I don't remember exactly, but it may well be that I should have used `-m` in the first place, and it just happened to work, like the comments in the pytest issue suggest.
