### PR TITLE
pytest 4.1 compatibility 

### LINKED ISSUE #18: Support pytest version >= 4.1
pytest-describe plugin is not working with pytest 4.0 or later. 

```
=========================================== ERRORS ============================================
_______________ ERROR collecting test/test_samples/pytest/test/describe_test.py _______________
.tox/py27/local/lib/python2.7/site-packages/pytest_describe/plugin.py:110: in _getobj
    return self._importtestmodule()
.tox/py27/local/lib/python2.7/site-packages/pytest_describe/plugin.py:119: in _importtestmodule
    copy_markinfo(module, self.funcobj)
.tox/py27/local/lib/python2.7/site-packages/pytest_describe/plugin.py:60: in copy_markinfo
    from _pytest.mark import MarkInfo
E   ImportError: cannot import name MarkInfo
!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================== 1 error in 0.75 seconds ===================================
```

This error appears for the test from sample 

```python
import pytest


def describe_list():

    @pytest.fixture
    def list():
        return []

    def describe_append():

        def adds_to_end_of_list_passed(list):
            list.append('foo')
            list.append('bar')
            assert list == ['foo', 'bar']

    def describe_remove():

        @pytest.fixture
        def list():
            return ['foo', 'bar']

        def removes_item_from_list_passed(list):
            list.remove('foo')
            assert list == ['bar']
```

It looks like this happens due to changes in mark API since version 4.0, for example, see https://github.com/pytest-dev/pytest/blob/master/doc/en/deprecations.rst#somefunctionmarkname.

### PR DESCRIPTION
**Pull request by kondratyev-nv**
Fixes #18

### CODE REVIEW

**Comment by ropez** [comment]
Thanks a lot. Will review this, and publish a new build, as soon as I can.

**Comment by ropez** [comment]
Looking at test output in travis.ci, there are a lot of invalid escape sequences in regular expressions:

```
test/test_collect.py:31
  /home/travis/build/ropez/pytest-describe/test/test_collect.py:31: DeprecationWarning: invalid escape sequence \s
    "\s*<DescribeBlock (')?describe_something(')?>",
```

These needs to be fixed, probably by using "raw" string literals, i.e change `"\s*..."` to `r"\s*..."`.

Example output: https://travis-ci.org/ropez/pytest-describe/jobs/487850038

**Comment by ropez** [comment]
I'll take care of the regexps

**Comment by kondratyev-nv** [comment]
Thank you! Sorry for a late reply, was going to fix it now, but you were faster :)

**Comment by ropez** [comment]
It's now published as version 0.12.0. Thank you @kondratyev-nv
